name: OpenFOAM 8

on:
  push:
    branches: [ master,  dev-CI]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: OpenFOAM8
      run: make runTestsOF8
